apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000 # Port your API is running on in the container
  type: LoadBalancer # Use LoadBalancer for exposing the service externally
