apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: blaiseregistry.azurecr.io/blaise:1.0 # Update with your ACR image details
          ports:
            - containerPort: 4000 # Adjust the port if your API uses a different port
